"""empty message

Revision ID: ea896291dad2
Revises: 6e270b38c8dc
Create Date: 2021-01-11 14:51:52.657907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea896291dad2'
down_revision = '6e270b38c8dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'produtos', ['nome'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'produtos', type_='unique')
    # ### end Alembic commands ###
